; generated by ARM C/C++ Compiler, 5.03 [Build 76]
; commandline ArmCC [--cpp --debug -c -S -o.\main.s --depend=.\main.d --cpu=Cortex-M3 --apcs=interwork -O0 -I..\h -ID:\Keil\ARM\RV31\INC -ID:\Keil\ARM\PACK\ARM\CMSIS\3.20.3\CMSIS\Include -ID:\Keil\ARM\PACK\Keil\STM32F1xx_DFP\1.0.2\Device\Include -D__MICROLIB -DSTM32F10X_MD -DSTM32F10X_MD --omf_browse=.\main.crf main.cpp]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

Task0 PROC
        B        |L0.18|
|L0.2|
        LDR      r0,|L0.108|
        LDR      r0,[r0,#0]
        CBNZ     r0,|L0.12|
        MOVS     r0,#1
        B        |L0.14|
|L0.12|
        MOVS     r0,#0
|L0.14|
        LDR      r1,|L0.108|
        STR      r0,[r1,#0]
|L0.18|
        B        |L0.2|
        ENDP

Task1 PROC
        B        |L0.38|
|L0.22|
        LDR      r0,|L0.112|
        LDR      r0,[r0,#0]
        CBNZ     r0,|L0.32|
        MOVS     r0,#1
        B        |L0.34|
|L0.32|
        MOVS     r0,#0
|L0.34|
        LDR      r1,|L0.112|
        STR      r0,[r1,#0]
|L0.38|
        B        |L0.22|
        ENDP

main PROC
        PUSH     {r4,lr}
		MRS		r4,msp
		PUSH	{pc}
		STR		0x800065b,[r4]
		POP		{pc}
        MOVS     r0,#0x44
        BL       _Znwj
        MOV      r4,r0
        ADR      r1,Task0 + 1
        ADDS     r1,r1,#1
        STR      r1,[r0,#0x1c]
        ADR      r2,Task1 + 1
        ADDS     r2,r2,#1
        STR      r2,[r0,#0x3c]
        MOVS     r1,#0
        STRB     r1,[r0,#0]
        MOVS     r1,#1
        STRB     r1,[r0,#1]
        NOP      
        LDR      r0,|L0.116|
        STR      r4,[r0,#0]  ; task
        BL       _Z4Initv
        MOV      r1,#0x1c1f
        MOVS     r0,#0x64
        BL       Timerx_Init
        MOVS     r0,#1
        LDR      r1,|L0.120|
        STRH     r0,[r1,#0]
        BL       Task0
        MOVS     r0,#0
        POP      {r4,pc}
        ENDP

|L0.108|
        DCD      0x422101a0
|L0.112|
        DCD      0x42228188
|L0.116|
        DCD      task
|L0.120|
        DCD      0x40000424

        AREA ||.ARM.exidx||, LINKORDER=||.text||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        DCD      0x00000000
        RELOC 42, ||.text||
        DCD      0x00000001

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

__ARM_use_no_argv EQU 0

        EXPORT __ARM_use_no_argv
        EXPORT Task0 [CODE]
        EXPORT Task1 [CODE]
        EXPORT main [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT ||Lib$$Request$$cpplib|| [CODE,WEAK]
        IMPORT _Znwj [CODE]
        IMPORT _Z4Initv [CODE]
        IMPORT Timerx_Init [CODE]
        IMPORT task [DATA]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,6,0
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
